version: "3"
services:
  analytics-postgis:
    image: ghcr.io/aasaam/geonames-postgis:latest
    container_name: analytics-postgis
    hostname: analytics-postgis

    environment:
      - POSTGRES_PASSWORD=geonames
      - POSTGRES_USER=geonames
      - POSTGRES_DB=geonames

    logging:
      driver: "journald"
      options:
        tag: "container:APP=analytics-clickhouse TYPE=postgres NODE_ID=${ASM_CH_CURRENT_NODE_ID}"

  analytics-redis:
    image: redis:7-alpine
    container_name: analytics-redis
    hostname: analytics-redis

  analytics-collector-producer:
    image: ghcr.io/aasaam/analytics-collector:latest
    depends_on:
      - analytics-redis
      - analytics-postgis
    container_name: analytics-collector-producer
    hostname: analytics-collector-producer
    command: run-producer

    env_file:
      - ./.env

    logging:
      driver: "journald"
      options:
        tag: "container:APP=analytics-clickhouse TYPE=golang-zerolog NODE_ID=${ASM_CH_CURRENT_NODE_ID}"

  analytics-collector-consumer:
    image: ghcr.io/aasaam/analytics-collector:latest
    depends_on:
      - analytics-redis
    container_name: analytics-collector-consumer
    hostname: analytics-collector-consumer
    command: run-consumer

    volumes:
      - ./cert:/cert:ro

    env_file:
      - ./.env

    extra_hosts:
      - "ch1.${ASM_CH_DOMAIN}:${ASM_CH_NODE1_IP}"
      - "ch2.${ASM_CH_DOMAIN}:${ASM_CH_NODE2_IP}"
      - "ch3.${ASM_CH_DOMAIN}:${ASM_CH_NODE3_IP}"

    logging:
      driver: "journald"
      options:
        tag: "container:APP=analytics-clickhouse TYPE=golang-zerolog NODE_ID=${ASM_CH_CURRENT_NODE_ID}"

  analytics-collector-nginx:
    image: ghcr.io/aasaam/analytics-collector-nginx:latest
    container_name: analytics-collector-nginx
    hostname: analytics-collector-nginx
    depends_on:
      - analytics-collector-producer
    ports:
      - 0.0.0.0:80:80
      - 0.0.0.0:443:443
    volumes:
      - ./public-cert:/cert:ro

    env_file:
      - ./.env

    logging:
      driver: "journald"
      options:
        tag: "container:APP=analytics-clickhouse TYPE=nginx NODE_ID=${ASM_CH_CURRENT_NODE_ID}"
