version: "3"

services:
  analytics-postgis:
    image: ghcr.io/aasaam/geonames-postgis:latest
    container_name: analytics-postgis
    hostname: analytics-postgis
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=geonames
      - POSTGRES_USER=geonames
      - POSTGRES_DB=geonames

  analytics-adminer:
    image: adminer
    container_name: analytics-adminer
    hostname: analytics-adminer
    depends_on:
      - analytics-postgis
    ports:
      - 8080:8080

  analytics-nginx:
    image: nginx:1-alpine
    container_name: analytics-nginx
    hostname: analytics-nginx
    network_mode: host
    # ports:
    #   - 443:443
    environment:
      ASM_NGX_WORKER_PROCESSES: ${ASM_NGX_WORKER_PROCESSES:-1}
      ASM_NGX_WORKER_RLIMIT_NOFILE: ${ASM_NGX_WORKER_RLIMIT_NOFILE:-512}
      ASM_NGX_ERROR_LOG_LEVEL: ${ASM_NGX_ERROR_LOG_LEVEL:-debug}
      ASM_NGX_WORKER_CONNECTIONS: ${ASM_NGX_WORKER_CONNECTIONS:-256}
      ASM_NGX_ACCESS_LOG_COMMENT: ${ASM_NGX_ACCESS_LOG_COMMENT:-}
      ASM_NGX_SSL_PROF_LEG_COMMENT: ${ASM_NGX_SSL_PROF_LEG_COMMENT:-}
      ASM_NGX_SSL_PROF_INT_COMMENT: ${ASM_NGX_SSL_PROF_INT_COMMENT:-#}
      ASM_NGX_SSL_PROF_MOD_COMMENT: ${ASM_NGX_SSL_PROF_MOD_COMMENT:-#}
      ASM_NGX_UPSTREAM: ${ASM_NGX_UPSTREAM:-http://127.0.0.1:4000}

    tmpfs:
      - /cache:rw,nodev,nosuid,noexec,noatime,size=${ASM_CACHE_SIZE_MB:-1024}m
    volumes:
      - ./nginx/.defaults:/defaults:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/template/default.conf:/etc/nginx/templates/default.conf.template:ro

      - ./nginx/cert:/cert:ro

volumes:
  clickhouse-db:
