version: "3"

services:
  analytics-postgis:
    image: ghcr.io/aasaam/geonames-postgis:latest
    container_name: analytics-postgis
    hostname: analytics-postgis
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=geonames
      - POSTGRES_USER=geonames
      - POSTGRES_DB=geonames

  analytics-adminer:
    image: adminer
    container_name: analytics-adminer
    hostname: analytics-adminer
    depends_on:
      - analytics-postgis
    ports:
      - 18080:8080

  analytics-nginx:
    image: ghcr.io/aasaam/nginx-extra:latest
    container_name: analytics-nginx
    hostname: analytics-nginx
    network_mode: host
    ports:
      - 80:80
      - 443:443
    environment:
      ASM_NGX_EXTRA_UPSTREAM: ${ASM_NGX_EXTRA_UPSTREAM:-http://127.0.0.1:4000}

    tmpfs:
      - /cache-fast:rw,nodev,nosuid,noexec,noatime,size=${ASM_NGX_EXTRA_PROXY_CACHE_FAST_SIZE:-192}m
    volumes:
      - ./nginx/nginx.conf:/template/nginx.conf:ro
      - ./nginx/cert:/cert:ro
