version: "3"

services:
  analytics-postgis:
    image: ghcr.io/aasaam/geonames-postgis:latest
    container_name: analytics-postgis
    hostname: analytics-postgis
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=geonames
      - POSTGRES_USER=geonames
      - POSTGRES_DB=geonames

  analytics-adminer:
    image: adminer
    container_name: analytics-adminer
    hostname: analytics-adminer
    depends_on:
      - analytics-postgis
    ports:
      - 8080:8080

  analytics-nginx:
    image: nginx:1-alpine
    container_name: analytics-nginx
    hostname: analytics-nginx
    network_mode: host
    # ports:
    #   - 443:443
    environment:
      ASM_NGX_WORKER_PROCESSES: ${ASM_NGX_WORKER_PROCESSES:-1}
      ASM_NGX_WORKER_RLIMIT_NOFILE: ${ASM_NGX_WORKER_RLIMIT_NOFILE:-512}
      ASM_NGX_ERROR_LOG_LEVEL: ${ASM_NGX_ERROR_LOG_LEVEL:-debug}
      ASM_NGX_WORKER_CONNECTIONS: ${ASM_NGX_WORKER_CONNECTIONS:-256}
      ASM_NGX_ACCESS_LOG_COMMENT: ${ASM_NGX_ACCESS_LOG_COMMENT:-}
      ASM_NGX_SSL_PROFILE: ${ASM_NGX_SSL_PROFILE:-legacy}
      ASM_NGX_UPSTREAM: ${ASM_NGX_UPSTREAM:-http://127.0.0.1:4000}

    tmpfs:
      - /cache:rw,nodev,nosuid,noexec,noatime,size=${ASM_CACHE_SIZE_MB:-1024}m
    volumes:
      - ./nginx/.defaults:/defaults:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/template/default.conf:/etc/nginx/templates/default.conf.template:ro

      - ./nginx/cert:/cert:ro

  analytics-clickhouse-single:
    image: clickhouse/clickhouse-server:22.3
    restart: always
    container_name: analytics-clickhouse-single
    hostname: analytics-clickhouse-single
    environment:
      # default password is `password123123`
      CLICKOUSE_PASSWORD_SHA256_HEX: ${CLICKOUSE_PASSWORD_SHA256_HEX:-933762e2bddba897d976a4dd8fc6c78fcf8288f8be646a0816aa0c40e287b207}
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - 9440:9440
      - 9999:9999
    volumes:
      - ./tmp/clickhouse-log:/var/log/clickhouse-server
      - clickhouse-db:/var/lib/clickhouse
      - ./clickhouse/cert:/cert:ro
      - ./clickhouse/config.d.dev:/etc/clickhouse-server/config.d:ro
      - ./clickhouse/users.xml:/etc/clickhouse-server/users.d/users.xml:ro

  analytics-clickhouse-client:
    image: clickhouse/clickhouse-server:22.3
    container_name: analytics-clickhouse-client
    hostname: analytics-clickhouse-client
    volumes:
      - ./clickhouse/config.d.dev:/etc/clickhouse-server/config.d:ro
      - ./clickhouse/schema.sql:/tmp/schema.sql
    entrypoint: tail -f /dev/null

volumes:
  clickhouse-db:
