version: "3"

services:
  analytics-postgis:
    image: ghcr.io/aasaam/geonames-postgis:latest
    container_name: analytics-postgis
    hostname: analytics-postgis
    environment:
      - POSTGRES_PASSWORD=geonames
      - POSTGRES_USER=geonames
      - POSTGRES_DB=geonames

  analytics-nginx:
    image: ghcr.io/aasaam/nginx-extra:latest
    container_name: analytics-nginx
    hostname: analytics-nginx
    ports:
      - 80:80
      - 443:443
    tmpfs:
      - /cache-fast:rw,nodev,nosuid,noexec,noatime,size=${ASM_NGX_EXTRA_PROXY_CACHE_FAST_SIZE:-192}m
    volumes:
      - ./nginx/cert:/cert:ro

  analytics-collector:
    image: ghcr.io/aasaam/analytics-collector:latest
    container_name: analytics-collector
    hostname: analytics-collector
    env_file:
      - ./.env
