version: "3"

services:
  analytics-collector:
    image: ghcr.io/aasaam/analytics-collector:latest
    container_name: analytics-collector
  postgis:
    image: ghcr.io/aasaam/geonames-postgis:latest
    container_name: geonames-postgis
    environment:
      - POSTGRES_PASSWORD=geonames
      - POSTGRES_USER=geonames
      - POSTGRES_DB=geonames
  web-server:
    image: ghcr.io/aasaam/web-server
    container_name: web-server
    network_mode: host
    tmpfs:
      - /cache:rw,nodev,nosuid,noexec,noatime,size=${ASM_CACHE_SIZE_MB:-1024}m
    volumes:
      - ./cert.prod/:/cert:ro
      - ./nginx/nginx.conf.tmpl:/usr/local/openresty/nginx/addon/gomplates/nginx.tmpl
  clickhouse-single:
      image: yandex/clickhouse-server:22
      restart: always
      container_name: clickhouse-single
      hostname: clickhouse-single
      environment:
        # default password is `password123123`
        CLICKOUSE_PASSWORD_SHA256_HEX: ${CLICKOUSE_PASSWORD_SHA256_HEX:-933762e2bddba897d976a4dd8fc6c78fcf8288f8be646a0816aa0c40e287b207}
      ulimits:
        nofile:
          soft: 262144
          hard: 262144
      ports:
        - 127.0.0.1:8123:8123
        - 127.0.0.1:9000:9000
        - 127.0.0.1:9009:9009
      volumes:
        - ./var/clickhouse/logs:/var/log/clickhouse-server
        - ./var/clickhouse/db:/var/lib/clickhouse
        - ./clickhouse/config.d.prod:/etc/clickhouse-server/config.d
        - ./clickhouse/users.xml:/etc/clickhouse-server/users.d/users.xml
  clickhouse-client:
      image: yandex/clickhouse-client:22
      container_name: clickhouse-client
      hostname: clickhouse-client
      volumes:
        - ./clickhouse/schema.sql:/tmp/schema.sql
      entrypoint: tail -f /dev/null
