version: "3"
services:
  analytics-clickhouse:
    image: clickhouse/clickhouse-server:22.3
    container_name: analytics-clickhouse
    hostname: ${ASM_CH_CURRENT_NODE_NAME}.${ASM_CH_DOMAIN}
    volumes:
      # storage
      - /data/persist/analytics-clickhouse/data:/var/lib/clickhouse/
      - /data/persist/analytics-clickhouse/logs:/var/log/clickhouse-server/

      # certificates
      - ./cert:/cert

      # configuration:schema
      - ./schema.sql:/schema.sql:ro

      # configuration:client
      - ./clickhouse-client/config.xml:/etc/clickhouse-client/config.xml:ro
      # configuration:server
      - ./clickhouse-server:/etc/clickhouse-server:ro

    env_file:
      - ./.env

    environment:
      - ASM_CH_CURRENT_NODE_HOSTNAME=${ASM_CH_CURRENT_NODE_NAME}.${ASM_CH_DOMAIN}
      - ASM_CH_OTHER_NODE_HOSTNAME_1=${ASM_CH_OTHER_NODE_NAME_1}.${ASM_CH_DOMAIN}
      - ASM_CH_OTHER_NODE_HOSTNAME_2=${ASM_CH_OTHER_NODE_NAME_2}.${ASM_CH_DOMAIN}
      - ASM_CH_REPLICA_NAME=${ASM_CH_CURRENT_NODE_NAME}-01

    cap_add:
      - SYS_NICE
      - NET_ADMIN
      - IPC_LOCK

    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144

    extra_hosts:
      - "ch01.${ASM_CH_DOMAIN}:${ASM_CH_NODE1_IP}"
      - "ch02.${ASM_CH_DOMAIN}:${ASM_CH_NODE2_IP}"
      - "ch03.${ASM_CH_DOMAIN}:${ASM_CH_NODE3_IP}"

    logging:
      driver: "journald"
      options:
        tag: "container:APP=analytics-clickhouse TYPE=clickhouse-replica NODE_ID=${ASM_CH_CURRENT_NODE_ID}"

  analytics-nginx-exposer:
    image: nginx:1-alpine
    container_name: analytics-nginx-exposer
    depends_on:
      - analytics-clickhouse
    ports:
      - "0.0.0.0:8443:8443" # HTTPS Port
      - "0.0.0.0:9440:9440" # TCP Port Secure
      - "0.0.0.0:9010:9010" # Interserver HTTPS Port
      - "0.0.0.0:9234:9234" # Raft Secure Port
      - "0.0.0.0:9234:9234/udp" # Raft Secure Port (UDP)
      - "0.0.0.0:9281:9281" # Keeper Server TCP Secure Port

    volumes:
      - ./nginx-exposer/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx-exposer/default.conf.template:/etc/nginx/templates/default.conf.template:ro
      - ./nginx-exposer/acl.conf:/acl.conf:ro

    env_file:
      - ./.env

    logging:
      driver: "journald"
      options:
        tag: "container:APP=analytics-clickhouse TYPE=nginx-exposer NODE_ID=${ASM_CH_CURRENT_NODE_ID} NGINX_STREAM_DOCKER_EXPOSER=1"

  analytics-postgis:
    image: ghcr.io/aasaam/geonames-postgis:latest
    container_name: analytics-postgis
    hostname: analytics-postgis

    environment:
      - POSTGRES_PASSWORD=geonames
      - POSTGRES_USER=geonames
      - POSTGRES_DB=geonames

    logging:
      driver: "journald"
      options:
        tag: "container:APP=analytics-clickhouse TYPE=postgres NODE_ID=${ASM_CH_CURRENT_NODE_ID}"

  analytics-collector:
    image: ghcr.io/aasaam/analytics-collector:latest
    depends_on:
      - analytics-postgis
    container_name: analytics-collector
    hostname: analytics-collector
    command: run

    volumes:
      - ./cert:/cert:ro

    env_file:
      - ./.env

    extra_hosts:
      - "ch01.${ASM_CH_DOMAIN}:${ASM_CH_NODE1_IP}"
      - "ch02.${ASM_CH_DOMAIN}:${ASM_CH_NODE2_IP}"
      - "ch03.${ASM_CH_DOMAIN}:${ASM_CH_NODE3_IP}"

    logging:
      driver: "journald"
      options:
        tag: "container:APP=analytics-clickhouse TYPE=golang NODE_ID=${ASM_CH_CURRENT_NODE_ID}"

  analytics-collector-nginx:
    image: ghcr.io/aasaam/analytics-collector-nginx:latest
    container_name: analytics-collector-nginx
    hostname: analytics-collector-nginx
    depends_on:
      - analytics-collector
    ports:
      - 0.0.0.0:80:80
      - 0.0.0.0:443:443
    volumes:
      - ./public-cert:/cert:ro
    env_file:
      - ./.env

    logging:
      driver: "journald"
      options:
        tag: "container:APP=analytics-clickhouse TYPE=nginx NODE_ID=${ASM_CH_CURRENT_NODE_ID}"
