name: build

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * 0"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASS }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        run: |

          ./make.sh

          docker build -t aasaam/analytics-collector .
          docker image inspect aasaam/analytics-collector:latest
          docker push aasaam/analytics-collector
          docker tag aasaam/analytics-collector ghcr.io/aasaam/analytics-collector:latest
          docker push ghcr.io/aasaam/analytics-collector:latest

          docker build -f Dockerfile.nginx -t aasaam/analytics-collector-nginx .
          docker push aasaam/analytics-collector-nginx
          docker tag aasaam/analytics-collector-nginx ghcr.io/aasaam/analytics-collector-nginx:latest
          docker push ghcr.io/aasaam/analytics-collector-nginx:latest

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASS }}
          repository: aasaam/analytics-collector
