name: test

on:
  push:
    branches:
      - "*"

jobs:
  golang:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - name: Test
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./make.sh
          echo ${{ github.ref }}
          go mod tidy
          go test -short -covermode=count -coverprofile=coverage.out
          cat coverage.out | grep -v "main.go" | grep -v "clickhouse.go" > coverage.txt
          TOTAL_COVERAGE_FOR_CI_F=$(go tool cover -func coverage.txt | grep total | grep -Eo '[0-9]+.[0-9]+')
          echo "TOTAL_COVERAGE_FOR_CI_F: $TOTAL_COVERAGE_FOR_CI_F"
